### PR TITLE
Make items in filter list auto tristate

### LINKED ISSUE #136: "Mask" and "Highlight" Checkbox Not Functional in PySide6 Migration
After upgrading the project from PySide2 to PySide6, I noticed an issue where the **Mask** and **Highlight** checkbox within the Color Options window is no longer clickable. The checkbox appears correctly, but clicking on it does not toggle its state as expected. This issue was not present when using PySide2.

Screenshot from 2024-03-15 23-23-14

openmc: 0.14.1
openmc-plotter: 0.4.0
pyside6: 6.6.2

### PR DESCRIPTION
**Pull request by paulromano**
If you have a mesh tally with other filters on top, right now it's not possible to pick out specific bins from those other filters. After digging into this a while, I realized that the problem was that the top-level treewidget items were not being set to "auto tristate", which allows them to be partially checked based on the state of the child items. With this change, now you can select bins for these filters freely. In my particular use case, I'm combining a material filter with a mesh filter and want to plot the mesh results restricted to a particular material.

### CODE REVIEW

**Comment by shimwell** [comment]
Oh this looks handy for shut down dose rate analysis, thanks Paul

**Comment by paulromano** [comment]
Just added one more fix for the cell/material highlight checkboxes in the color options dialog not working.

**Review by pshriwise — APPROVED** [review]
LGTM. Thanks @paulromano!

**Comment by pshriwise** [comment]
> Just added one more fix for the cell/material highlight checkboxes in the color option

I noticed that too yesterday. Thanks!

**Pull request merged**
