### PR TITLE
Allow user to change default resolution from command line

### LINKED ISSUE #139: Set initial number of pixels from command line
First noted in #138, for very large models it can be useful to reduce the number of pixels to increase interactivity until a view is chosen. There's currently no way to control this for the first image generated unless a settings file is hanging around from a previous session. It would be useful to be able to set the initial image size (in pixels) as a command line argument.

### PR DESCRIPTION
**Pull request by paulromano**
Relatively small PR adding ability to change the default resolution with a `-r`/`--resolution` switch from the command line. 

Closes #139

### CODE REVIEW

**Comment by pshriwise** [comment]
Really nice idea when dealing with large models or DAGMC models. What would you think of updating the current view's resolution as well if this flag is passed? Then the view and plot settings from a previous session can be maintained when opening the plotter.

**Comment by paulromano** [comment]
I'm a little confused by your suggestion. The view and plot settings from a previous session _are_ preserved even if the `-r` flag is passed since it only affects the view settings if no `plot_settings.pkl` file was present. Can you elaborate?

**Comment by pshriwise** [comment]
I guess when I opened #138, I was thinking that the resolution value would be applied to the image seen when opening the application which could be the default view or the last view from a previous session. The idea here being if the plotter is generally taking a long time to open (regardless of whether it's loading the default view or not), the value can be provided to reduce the loading time for the GUI to get a first image and start the session.

To leverage this feature for a previous session, a user would have to discard the last view of a previous session, which for large models may have taken some time to locate, using the `-e` flag. They could save this as a view file, but the current image resolution is also stored in that file, so I don't that that's a solution either. 

If the resolution is low, it's quick to move around in any model and get back to the last view from another session, but all-in-all I wouldn't mind seeing this setting apply to the initial image rather than the default `PlotView` object.

**Comment by paulromano** [comment]
@pshriwise Thanks for the explanation. I've just updated the branch so that a specified resolution can apply to a restored view.

**Review by pshriwise — APPROVED** [review]
Just retested this and it's working great! Thanks for this feature @paulromano!

**Pull request merged**
